# Generated by Django 5.0.4 on 2024-06-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_colors_alter_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sex',
            field=models.CharField(choices=[('Male', 'Erkak'), ('Female', 'Ayol')], default='Filmale', max_length=20),
            preserve_default=False,
        ),
    ]
