# Generated by Django 5.0.4 on 2024-06-18 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_customuser_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='payment_id',
        ),
    ]
